const products=[
 {name:'Premium finger millet',store:'Kijani Grain Farm',price:280,category:'Grains',emoji:'🌾',tag:'New harvest',bg:'#efe4c8'},
 {name:'Red sorghum grain',store:'Rift Valley Growers',price:240,category:'Grains',emoji:'🌾',tag:'Naturally grown',bg:'#eadbc5'},
 {name:'Pishori rice',store:'Mwea Rice Fields',price:360,category:'Grains',emoji:'🍚',tag:'Aromatic',bg:'#e8eee1'},
 {name:'Hass avocados',store:'Kiambu Avocado Farm',price:450,category:'Fruit',emoji:'🥑',tag:'Ready to eat',bg:'#dcebcf'},
 {name:'Fresh cassava',store:'Coastal Roots Farm',price:180,category:'Roots',emoji:'🥔',tag:'Harvested today',bg:'#eee2cd'},
 {name:'Orange sweet potatoes',store:'Nyeri Harvest Co.',price:220,category:'Roots',emoji:'🍠',tag:'Sweet & nutritious',bg:'#f0d1b6'},
 {name:'Green sukuma wiki',store:'Mama Naliaka Greens',price:70,category:'Vegetables',emoji:'🥬',tag:'Farm fresh',bg:'#d9ead4'},
 {name:'Red kidney beans',store:'Rift Valley Growers',price:320,category:'Legumes',emoji:'🫘',tag:'High protein',bg:'#e8d8d0'},
 {name:'Fresh tomatoes',store:'Mavuno Market Garden',price:140,category:'Vegetables',emoji:'🍅',tag:'Picked today',bg:'#f0d5cc'},
 {name:'Ripe bananas',store:'Kisii Fresh Farms',price:160,category:'Fruit',emoji:'🍌',tag:'Sweet & ripe',bg:'#f4e8ae'},
 {name:'Aromatic coriander',store:'Mavuno Market Garden',price:60,category:'Herbs',emoji:'🌿',tag:'Fresh bundle',bg:'#dcebd9'},
 {name:'Quality maize flour',store:'Kijani Grain Farm',price:145,category:'Grains',emoji:'🌽',tag:'Stone milled',bg:'#f2e5ba'}
 {name:'Organic carrots',store:'Mama Naliaka Greens',price:90,category:'Vegetables',emoji:'🥕',tag:'Crisp & sweet',bg:'#f4d1b6'},
    {name:'Fresh spinach',store:'Mama Naliaka Greens',price:80,category:'Vegetables',emoji:'🥬',tag:'Picked today',bg:'#d9ead4'},
    {name:'Sweet bell peppers',store:'Mavuno Market Garden',price:120,category:'Vegetables',emoji:'🫑',tag:'Colorful & fresh',bg:'#f0d5cc'},
];
const stores=[['🌾','Kijani Grain Farm','Millet, sorghum, maize & grains'],['🥑','Kiambu Avocado Farm','Creamy Hass avocados, farm direct'],['🍚','Mwea Rice Fields','Premium Kenyan rice'],['🍠','Nyeri Harvest Co.','Wholesome roots and tubers'],['🥬','Mama Naliaka Greens','Daily-picked leafy vegetables'],['🍅','Mavuno Market Garden','Fruit, herbs and vegetables']];
let cart=[];let currentFilter='all';
const fmt=n=>'KSh '+n.toLocaleString();
function renderProducts(){const visible=currentFilter==='all'?products:products.filter(p=>p.category===currentFilter);document.getElementById('productGrid').innerHTML=visible.map((p,i)=>`<article class="product-card"><div class="product-image" style="background:${p.bg}"><span class="tag">${p.tag}</span><button class="wish" aria-label="Save ${p.name}">♡</button><span>${p.emoji}</span></div><div class="product-info"><span class="store-name">${p.store}</span><h3>${p.name}</h3><div class="product-bottom"><span class="price">${fmt(p.price)}</span><span class="rating">★ 4.${8+i%2}</span><button class="add-btn" data-id="${products.indexOf(p)}">Add +</button></div></div></article>`).join('');document.querySelectorAll('.add-btn').forEach(b=>b.onclick=()=>addToCart(+b.dataset.id));}
function renderStores(){document.getElementById('storeGrid').innerHTML=stores.map(s=>`<article class="store-card"><div class="store-icon">${s[0]}</div><div><h3>${s[1]}</h3><p>${s[2]}</p></div><button class="visit-store">Visit store →</button></article>`).join('');}
function addToCart(id){cart.push(products[id]);renderCart();document.getElementById('toast').classList.add('show');setTimeout(()=>document.getElementById('toast').classList.remove('show'),2200)}
function renderCart(){const count=document.getElementById('cartCount'),items=document.getElementById('cartItems'),total=cart.reduce((s,p)=>s+p.price,0);count.textContent=cart.length;items.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><div class="cart-emoji">${p.emoji}</div><div><h4>${p.name}</h4><p>${fmt(p.price)}</p></div><button aria-label="Remove ${p.name}" data-remove="${i}">×</button></div>`).join(''):'<p class="empty-cart">Your cart is waiting for something lovely.</p>';document.getElementById('cartTotal').textContent=fmt(total);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()});}
const panel=document.getElementById('cartPanel'),overlay=document.getElementById('overlay'),modal=document.getElementById('storeModal');
function showCart(){panel.classList.add('open');overlay.classList.add('open')}function closeOverlays(){panel.classList.remove('open');overlay.classList.remove('open');modal.classList.remove('open')}
document.getElementById('cartButton').onclick=showCart;document.getElementById('closeCart').onclick=closeOverlays;overlay.onclick=closeOverlays;
document.querySelectorAll('.category').forEach(c=>c.onclick=()=>{document.querySelector('.category.active').classList.remove('active');c.classList.add('active');currentFilter=c.dataset.filter;renderProducts();document.getElementById('products').scrollIntoView({behavior:'smooth'})});
document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();const q=document.getElementById('searchInput').value.trim().toLowerCase();currentFilter='all';document.querySelector('.category.active').classList.remove('active');document.querySelector('.category').classList.add('active');document.getElementById('productGrid').innerHTML='';renderProducts();if(q){const matching=[...document.querySelectorAll('.product-card')].filter((card,i)=>products[i].name.toLowerCase().includes(q)||products[i].store.toLowerCase().includes(q));document.querySelectorAll('.product-card').forEach(el=>el.style.display='none');matching.forEach(el=>el.style.display='block')}document.getElementById('products').scrollIntoView({behavior:'smooth'})};
document.querySelectorAll('.open-store').forEach(b=>b.onclick=()=>{modal.classList.add('open');overlay.classList.add('open')});document.querySelector('.modal-close').onclick=closeOverlays;document.getElementById('startStore').onclick=()=>{window.location.href='dashboard.html'};document.getElementById('nextProducts').onclick=()=>document.getElementById('products').scrollIntoView({behavior:'smooth'});document.getElementById('prevProducts').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});renderProducts();renderStores();
